In [2]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('moria.jpg')
img = img[:,:,::-1]

median = cv2.medianBlur(img,9)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(median),plt.title('median')
plt.xticks([]), plt.yticks([])
plt.show()

In [4]:
img = cv2.imread('moria.jpg')
median = cv2.medianBlur(img,9)
cv2.namedWindow('img', cv2.WINDOW_NORMAL)
cv2.namedWindow('median', cv2.WINDOW_NORMAL)
cv2.imshow('img',img)
cv2.imshow('median',median)
if cv2.waitKey(0):
    cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('moria.jpg',0)
f = np.fft.fft2(img)
fshift = np.fft.fftshift(f)
magnitude_spectrum = 20*np.log(np.abs(fshift))

plt.subplot(121),plt.imshow(img, cmap = 'gray')
plt.title('Input Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(magnitude_spectrum, cmap = 'gray')
plt.title('Magnitude Spectrum'), plt.xticks([]), plt.yticks([])
plt.show()

In [6]:
rows, cols = img.shape
crow,ccol = rows/2 , cols/2
fshift[crow-30:crow+30, ccol-30:ccol+30] = 0
f_ishift = np.fft.ifftshift(fshift)
img_back = np.fft.ifft2(f_ishift)
img_back = np.abs(img_back)

plt.subplot(131),plt.imshow(img, cmap = 'gray')
plt.title('Input Image'), plt.xticks([]), plt.yticks([])
plt.subplot(132),plt.imshow(img_back, cmap = 'gray')
plt.title('Image after HPF'), plt.xticks([]), plt.yticks([])
plt.subplot(133),plt.imshow(img_back)
plt.title('Result in JET'), plt.xticks([]), plt.yticks([])

plt.show()

In [7]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

img = cv2.imread('moria.jpg',0)

dft = cv2.dft(np.float32(img),flags = cv2.DFT_COMPLEX_OUTPUT)
dft_shift = np.fft.fftshift(dft)

magnitude_spectrum = 20*np.log(cv2.magnitude(dft_shift[:,:,0],dft_shift[:,:,1]))

plt.subplot(121),plt.imshow(img, cmap = 'gray')
plt.title('Input Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(magnitude_spectrum, cmap = 'gray')
plt.title('Magnitude Spectrum'), plt.xticks([]), plt.yticks([])
plt.show()

In [16]:
img = cv2.imread('moria.jpg',0)
rows, cols = img.shape
crow,ccol = rows/2 , cols/2

# create a mask first, center square is 1, remaining all zeros
mask = np.zeros((rows,cols,2),np.uint8)
mask[crow-200:crow+200, ccol-200:ccol+200] = 1

# apply mask and inverse DFT
fshift = dft_shift*mask
f_ishift = np.fft.ifftshift(fshift)
img_back = cv2.idft(f_ishift)
img_back = cv2.magnitude(img_back[:,:,0],img_back[:,:,1])

plt.subplot(121),plt.imshow(img, cmap = 'gray')
plt.title('Input Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(img_back, cmap = 'gray')
plt.title('Magnitude Spectrum'), plt.xticks([]), plt.yticks([])
plt.show()

In [42]:
img = cv2.imread('moria2.jpg',0)
rows, cols = img.shape
crow,ccol = rows/2 , cols/2

# create a mask first, center square is 1, remaining all zeros
mask = np.zeros((rows,cols,2),np.uint8)
mask[crow-200:crow+200, ccol-200:ccol+200] = 1

dft = cv2.dft(np.float32(img),flags = cv2.DFT_COMPLEX_OUTPUT)
dft_shift = np.fft.fftshift(dft)
# apply mask and inverse DFT
fshift = dft_shift*mask
f_ishift = np.fft.ifftshift(fshift)
img_back = cv2.idft(f_ishift)
img_back = cv2.magnitude(img_back[:,:,0],img_back[:,:,1])

plt.subplot(121),plt.imshow(img, cmap = 'gray')
plt.title('Input Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(img_back, cmap = 'gray')
plt.title('Magnitude Spectrum'), plt.xticks([]), plt.yticks([])
plt.show()

In [43]:
dft_shift.shape

(2160L, 2880L, 2L)

In [44]:
dft.shape

(2160L, 2880L, 2L)

In [45]:
img.shape

(2160L, 2880L)

In [33]:
mask

array([[[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       ..., 
       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ..., 
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=uint8)

In [34]:
mask.shape

(2160L, 2880L, 2L)

In [35]:
img.shape

(2160L, 2880L)

In [39]:
np.zeros((3,3,2),np.uint8)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=uint8)

In [13]:
rows, cols

(2160L, 2880L)

In [2]:
img=numpy.zeros((3,3), dtype=numpy.uint8)

In [3]:
img

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [4]:
img=cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

In [5]:
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [6]:
img.shape

(3L, 3L, 3L)

In [7]:
img=cv2.imread('DSC08475.jpg')

In [8]:
img

array([[[235, 223, 217],
        [234, 222, 216],
        [233, 221, 215],
        ..., 
        [ 32,  43,  51],
        [ 34,  45,  53],
        [ 35,  46,  54]],

       [[234, 222, 216],
        [233, 221, 215],
        [233, 221, 215],
        ..., 
        [ 39,  48,  57],
        [ 39,  48,  57],
        [ 38,  47,  56]],

       [[233, 224, 215],
        [232, 223, 214],
        [232, 223, 214],
        ..., 
        [ 43,  51,  58],
        [ 43,  49,  56],
        [ 42,  48,  55]],

       ..., 
       [[ 92,  90, 126],
        [ 91,  89, 125],
        [ 90,  88, 124],
        ..., 
        [ 85,  83,  83],
        [ 86,  81,  82],
        [ 86,  81,  82]],

       [[ 91,  89, 125],
        [ 91,  89, 125],
        [ 92,  90, 126],
        ..., 
        [ 85,  83,  83],
        [ 85,  83,  83],
        [ 87,  82,  83]],

       [[ 90,  89, 123],
        [ 91,  90, 124],
        [ 93,  92, 126],
        ..., 
        [ 82,  80,  80],
        [ 83,  81,  81],
        [ 85,  80,

In [11]:
img.shape

(3264L, 4912L, 3L)

In [12]:
cv2.imwrite('mypic.png', img)

True

In [13]:
image=cv2.imread('DSC08475.jpg')

In [14]:
cv2.imwrite('mypic.bmp', image)

True

In [15]:
grayimage=cv2.imread('DSC08475.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imwrite('mypic.jpg', grayimage)

True