In [3]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('IMG_4775.jpg')
img = img[:,:,::-1]

blur = cv2.blur(img,(5,5))

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('Blurred')
plt.xticks([]), plt.yticks([])
plt.show()

In [4]:
img = cv2.imread('IMG_4775.jpg')
img = img[:,:,::-1]

blur = cv2.GaussianBlur(img,(5,5),0)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('Blurred')
plt.xticks([]), plt.yticks([])
plt.show()

In [6]:
img = cv2.imread('IMG_4775.jpg')
img = img[:,:,::-1]

median = cv2.medianBlur(img,5)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(median),plt.title('median')
plt.xticks([]), plt.yticks([])
plt.show()

In [9]:
img = cv2.imread('moria.jpg')
img = img[:,:,::-1]

median = cv2.medianBlur(img,9)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(median),plt.title('median')
plt.xticks([]), plt.yticks([])
plt.show()

In [12]:
img = cv2.imread('moria.jpg')
img = img[:,:,::-1]

blur =  cv2.blur(img,(5,5))

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(blur),plt.title('blur')
plt.xticks([]), plt.yticks([])
plt.show()

In [15]:
img = cv2.imread('moria2.jpg')
img = img[:,:,::-1]

median = cv2.medianBlur(img,9)

plt.subplot(121),plt.imshow(img),plt.title('Original')
plt.xticks([]), plt.yticks([])
plt.subplot(122),plt.imshow(median),plt.title('median')
plt.xticks([]), plt.yticks([])
plt.show()

In [26]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('IMAG2072.jpg',0)
edges1 = cv2.Canny(img,100,120)
edges2 = cv2.Canny(img,100,200)
edges3 = cv2.Canny(img,100,600)

plt.subplot(141),plt.imshow(img,cmap = 'gray')
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(142),plt.imshow(edges1,cmap = 'gray')
plt.title('Edge1 Image'), plt.xticks([]), plt.yticks([])
plt.subplot(241),plt.imshow(edges2,cmap = 'gray')
plt.title('Edge2 Image'), plt.xticks([]), plt.yticks([])
plt.subplot(242),plt.imshow(edges3,cmap = 'gray')
plt.title('Edge3 Image'), plt.xticks([]), plt.yticks([])

plt.show()

In [30]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('IMAG2072.jpg',0)

laplacian = cv2.Laplacian(img,cv2.CV_64F)
sobelx = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)

plt.subplot(2,2,1),plt.imshow(img,cmap = 'gray')
plt.title('Original'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,2),plt.imshow(laplacian,cmap = 'gray')
plt.title('Laplacian'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,3),plt.imshow(sobelx,cmap = 'gray')
plt.title('Sobel X'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,4),plt.imshow(sobely,cmap = 'gray')
plt.title('Sobel Y'), plt.xticks([]), plt.yticks([])

plt.show()

In [33]:
import cv2
import numpy as np

filename = 'IMAG2072.jpg'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)

#result is dilated for marking the corners, not important
dst = cv2.dilate(dst,None)

# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.01*dst.max()]=[0,0,255]

cv2.namedWindow('dst', cv2.WINDOW_NORMAL)
cv2.imshow('dst',img)
if cv2.waitKey(0):
    cv2.destroyAllWindows()

In [2]:
img=numpy.zeros((3,3), dtype=numpy.uint8)

In [3]:
img

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [4]:
img=cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

In [5]:
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [6]:
img.shape

(3L, 3L, 3L)

In [7]:
img=cv2.imread('DSC08475.jpg')

In [8]:
img

array([[[235, 223, 217],
        [234, 222, 216],
        [233, 221, 215],
        ..., 
        [ 32,  43,  51],
        [ 34,  45,  53],
        [ 35,  46,  54]],

       [[234, 222, 216],
        [233, 221, 215],
        [233, 221, 215],
        ..., 
        [ 39,  48,  57],
        [ 39,  48,  57],
        [ 38,  47,  56]],

       [[233, 224, 215],
        [232, 223, 214],
        [232, 223, 214],
        ..., 
        [ 43,  51,  58],
        [ 43,  49,  56],
        [ 42,  48,  55]],

       ..., 
       [[ 92,  90, 126],
        [ 91,  89, 125],
        [ 90,  88, 124],
        ..., 
        [ 85,  83,  83],
        [ 86,  81,  82],
        [ 86,  81,  82]],

       [[ 91,  89, 125],
        [ 91,  89, 125],
        [ 92,  90, 126],
        ..., 
        [ 85,  83,  83],
        [ 85,  83,  83],
        [ 87,  82,  83]],

       [[ 90,  89, 123],
        [ 91,  90, 124],
        [ 93,  92, 126],
        ..., 
        [ 82,  80,  80],
        [ 83,  81,  81],
        [ 85,  80,

In [11]:
img.shape

(3264L, 4912L, 3L)

In [12]:
cv2.imwrite('mypic.png', img)

True

In [13]:
image=cv2.imread('DSC08475.jpg')

In [14]:
cv2.imwrite('mypic.bmp', image)

True

In [15]:
grayimage=cv2.imread('DSC08475.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imwrite('mypic.jpg', grayimage)

True